mixed-port: 7890
socks-port: 7891
redir-port: 7892
allow-lan: true
mode: rule
log-level: info
external-controller: 0.0.0.0:9090
external-ui: yacd-gh-pages
dns:
  enable: true
  ipv6: false
  listen: 0.0.0.0:1053
  enhanced-mode: redir-host # fake-ip
  fake-ip-filter:
    - 'stun.*.*'
    - 'stun.*.*.*'
    - 'stun.*.*.*.*'
  nameserver:
#    - 192.168.88.1:53
    - 223.5.5.5
    - 114.114.114.114    
#    - 211.137.130.2:53
#    - 221.11.1.67:53
#    - 1.1.1.1
  fallback:
    - https://162.159.36.1/dns-query
    - https://1.1.1.1/dns-query
    - https://dns.google/dns-query
tun:
  enable: true
  stack: system # or gvisor
  # dns-hijack:
  #   - 8.8.8.8:53
  #   - tcp://8.8.8.8:53